---
- name: Install Apache and PHP on CentOS
  hosts: CentOS
  become: yes
  tasks:
    - name: Install Apache and PHP packages
      package:
        name:
          - httpd
          - php
        state: latest
 
    - name: Start and enable Apache
      service:
        name: "{{ apache_package}}"
        state: started
        enabled: true

    - name: Open HTTP port in firewall
      firewalld:
        port: 80/tcp
        permanent: yes
        state: enabled
        immediate: yes
